# We'd like to use the Docker infrastructure,
# but can't install libgrpc-dev at present in that environment. Sigh.
# sudo: false
sudo: true


language: ruby
cache: bundler
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0

before_install:
  - git clone https://github.com/murgatroid99/grpc.git
  - cd grpc
  - git checkout ruby_bundle_core_release
  - gem build grpc.gemspec
  - gem install --local --force grpc-*.gem
  - mkdir -p ../vendor/cache
  - cp grpc-*.gem ../vendor/cache
  - cd ..
  - rm -rf grpc

script:
 - bundle exec rake
